# dataset setting
inter_path : './dataset/Beauty_2014/beauty.inter'
text_feat_path : './dataset/Beauty_2014/text_feat.pt'
image_feat_path : './dataset/Beauty_2014/image_feat.pt'

num_epochs : 500
eval_every : 1
test_every : 5
num_workers : 8
max_no_improvement : 10

num_users : 22363
num_items : 12101

max_seq_len : 50

attn_embed_dim : 256
text_dim : 768
visual_dim : 768
hidden_size : 256

lr_factor : 0.1

train_batch_size : 2048
test_batch_size : 2048

attn_layers : 4

weight_decay : 0.01
top_k : 50

dropout : 0.1
attn_heads : 8
emb_dropout : 0.3


